### PR TITLE
Migrate startup_namer to null-safety

### PR DESCRIPTION
**Pull request by miquelbeltran**
Hello! :wave:

I am working with @RedBrogdon and @sfshaza2 on migrating the codelab: https://github.com/flutter/website/blob/master/src/docs/get-started/codelab.md to null safety, so I wanted to update the codelab code first.

What I did is to follow the instructions to migrate codelabs by making a copy with `_migrated`, so I copied the codelab `startup_namer` to `startup_namer_migrated`. If you want me to replace the original one, let me know.

The codelab code is mostly unchanged, all changes are on the pubspecs and the test files. You can go commit by commit to review the changes.

### CODE REVIEW

**Comment by domesticmouse** [comment]
I'd prefer this be an update to the original `startup_namer`. @RedBrogdon are we doing a `beta` branch for codelabs, or should we do individual codelab updates?

**Comment by RedBrogdon** [comment]
As annoying as it is, we need to have both versions of the codelab present in this repo for a time. It's because we need to land the updated codelab on the website *without* removing the unmigrated version, and the automatic code excerpt tools that the website uses will break if they can't find both sources in the submodule of this repo that's present in flutter/website.

Once we no longer need the unmigrated version on the website, It'll be deleted, and the old version of startup_namer can go to codelab heaven as well.

**Comment by miquelbeltran** [comment]
I noticed one thing when testing the codelab once again, is that the method `ListTile.divideTiles(context, tiles, color)` will throw an exception when passed an empty list. This causes the codelab to show a red error screen if the learner tabs on the AppBar icon added in Step 7 without having added a word into the saved list.

The issue only happens when null-safety is enabled, as I wasn't able to reproduce it in with the codelab without null safety.

I have created a ticket on the Flutter repo: https://github.com/flutter/flutter/issues/75518

**Comment by domesticmouse** [comment]
In which case rename to `startup_namer_null_safety` or similar

**Comment by miquelbeltran** [comment]
@domesticmouse I renamed the folder now.

Also, the issue found in `divideTiles` is fixed and should be merged eventually into the flutter framework.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Do you think the problem is serious enough that the fix should be cherry picked into the beta branch, or can we live with it for a quarter?

**Comment by miquelbeltran** [comment]
If the developer follows all steps in the codelab, they shouldn't see the error, as the codelab asks to first "Favorite some of the selections" and then "tap the list icon in the app bar", so that shouldn't show the error.

So... I don't think it breaks the codelab, but it could create a bit of confusion if someone forgets to add favorites first. I am not really qualified to say if it should be cherry-picked :smile: but since it doesn't break the codelab completely I would say is ok to wait.

**Comment by domesticmouse** [comment]
Thanks @miquelbeltran 😎

**Comment by domesticmouse** [comment]
Can you please add `startup_namer_null_safety` to both https://github.com/miquelbeltran/codelabs/blob/mb-startup_namer-nullsafety/flutter_ci_script_beta.sh and https://github.com/miquelbeltran/codelabs/blob/mb-startup_namer-nullsafety/flutter_ci_script_dev.sh so this code gets tested in CI? 

Also, please add it as a commented out entry to https://github.com/miquelbeltran/codelabs/blob/mb-startup_namer-nullsafety/flutter_ci_script_stable.sh with a comment along the lines of `TODO(domesticmouse): uncomment when  null safety goes stable`. See https://github.com/flutter/codelabs/pull/68/files#diff-3ffbbcd67b9b8baf27a025535e25c713091b23394b18ba7f35278ac4c42f0fd3 for an example.

Thanks!

**Review by domesticmouse — APPROVED** [review]
Thanks!

**Pull request merged**
