### PR TITLE
Scaffold.showSnackBar() -> ScaffoldMessenger.showSnackBar()

### PR DESCRIPTION
**Pull request by domesticmouse**
Fixes: https://github.com/flutter/flutter/issues/72325
Also needed for: https://github.com/flutter/flutter/issues/74209

FYI @abd99 

Hold until post Flutter 1.22 stable

### CODE REVIEW

**Comment by abd99** [comment]
Thanks for the PR, @domesticmouse! We'll wait until `ScaffoldMessenger` lands into the stable branch. I also need to make these changes to the sample app.

**Comment by domesticmouse** [comment]
Thanks @abd99, please feel free to cc me on any PRs you raise so I can lgtm them. =)

**Comment by RedBrogdon** [comment]
Gentle ping @filiph.

**Review by filiph — APPROVED** [review]
LGTM, thanks Brett! Also, apologies for taking this long to reply — this totally got buried in my inbox.

**Comment by domesticmouse** [comment]
Thanks @filiph, this PR still has a little while yet before it can land 🤪

**Pull request merged**
