### PR TITLE
Fixing up issues with home screen codelab

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
Eric, can you explain the following CI error?

```console
Error parsing LocalFile: '/home/runner/work/codelabs/codelabs/homescreen_codelab/step_05/android/app/src/main/AndroidManifest.xml' Please ensure that the android manifest is a valid XML document and try again.
```

**Comment by ericwindmill** [comment]
Very strange error to see for the first time, I don't know how that could've slipped past me. The Manifest XML doc was missing a closing tag.

**Comment by ericwindmill** [comment]
> Eric, can you explain the following CI error?
> 
> ```
> Error parsing LocalFile: '/home/runner/work/codelabs/codelabs/homescreen_codelab/step_05/android/app/src/main/AndroidManifest.xml' Please ensure that the android manifest is a valid XML document and try again.
> ```

Very strange error to see for the first time, I don't know how that could've slipped past me. The Manifest XML doc was missing a closing tag.

**Comment by domesticmouse** [comment]
The home screen lab wasn't under CI

**Comment by domesticmouse** [comment]
Also, please LGTM so we can land it 😎

**Review by parlough — APPROVED** [review]

**Review by ericwindmill — APPROVED** [review]
LGTM

**Pull request merged**
