### PR TITLE
`webview_flutter`: add `setCookie` to step 11

### PR DESCRIPTION
**Pull request by JDDV**
Updated step 11: Added the `_onSetCookie` method which uses the recently added `setCookie` method from the `CookieManager` class.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
Has this also been added to the Codelab document?

**Review by domesticmouse — APPROVED** [review]
Before this is landed it should be reflected in the codelab text.

**Comment by mvanbeusekom** [comment]
@domesticmouse no it hasn't. Like discussed offline we created a PR first so we could judge if it will fit in de current document or if it is better to write a separate codelab

**Comment by domesticmouse** [comment]
Ahh, so there is more changes inbound?

**Comment by mvanbeusekom** [comment]
Yes, but not regarding this "managing cookies" topic. 

We want to document one more topic which is related to loading Flutter Assets, files and HTML strings in the webview.

**Comment by domesticmouse** [comment]
This one makes sense to go into the current codelab as is. Are you happy to roll up the other topic as a separate PR?

**Comment by mvanbeusekom** [comment]
Yes I think that would make the most sense. I will make sure this content gets added to the current codelab and submit a different PR for the advanced loading features and we can discuss there how to document those features.

**Comment by domesticmouse** [comment]
I can handle adding it to the codelab. I'll land this when the updated codelab is published to codelabs.developers.google.com.

**Pull request merged**
