### PR TITLE
`cookbook` Add codelab rebuild script

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon

**Comment by RedBrogdon** [comment]
I'm going to punt this one toward Khanh, since the cookbook ends up on docs.flutter.dev, and it'd be good for her to have a view of the process.

Khanh, if you'd already reviewed some of these and are already so familiar that you're bored with the process, feel free to punt it back. 😄

**Comment by domesticmouse** [comment]
This one should have zero impact on `flutter/website` because it only changes the Runners, which I don't think the website cookbooks reference. I added the full Flutter project to this directory to enable CI linters over the cookbook Flutter code.

**Comment by domesticmouse** [comment]
PTAL @khanhnwin

**Review by khanhnwin — APPROVED** [review]
LGTM, but @domesticmouse I might set up a meeting with you a little later on to get a better understanding of this!

**Comment by domesticmouse** [comment]
> LGTM, but @domesticmouse I might set up a meeting with you a little later on to get a better understanding of this!

Sounds good to me, i need to figure out how to document this tool

**Pull request merged**
