### PR TITLE
`tfserving`: `connectionModeType` -> `ConnectionModeType`

### PR DESCRIPTION
**Pull request by domesticmouse**
Renaming enum to make the code lint clean on Flutter beta channel

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @windmaple. Your code will trigger lint warnings in the next revision of Flutter. Can you please update your codelab to match this code so we can land this PR?

**Comment by windmaple** [comment]
LGTM

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon

**Review by RedBrogdon — APPROVED** [review]

**Comment by domesticmouse** [comment]
@windmaple this has landed, please update the codelab text. Thanks!

**Pull request merged**
