### PR TITLE
`next-gen-ui` Dart 3 patterns refactor

### PR DESCRIPTION
**Pull request by miquelbeltran**
I have updated the codelab_rebuild as well and the patch change seems to fine.

Once reviewed I will update the codelab document.

## Pre-launch Checklist

- [ ] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by miquelbeltran** [comment]
I messed up my branches, will fix this. I keep the PR open.

**Comment by miquelbeltran** [comment]
fixed now

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Have I shared the gDoc with you @miquelbeltran?

**Comment by miquelbeltran** [comment]
Yes, I had reviewed the doc in the past. I will do the document changes today and let you know when ready.

**Comment by miquelbeltran** [comment]
sorry for the delay, the document is now updated

**Comment by miquelbeltran** [comment]
> I'm guessing this is no longer WIP? =)

oops, yes, it is ready to review and merge

**Pull request merged**
