### PR TITLE
Fix compile errors, downgrade camelcase-keys to 6.2.2

### PR DESCRIPTION
**Pull request by simonpham**
This PR fixes issue [#108939](https://github.com/flutter/flutter/issues/108939)

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jugidev** [comment]
I reviewed your PR and tried to apply it to my code, but I ran into issues deploying it to firebase. So I fixed deploying of my functions with updating all dependencies to latest version and raised node version for functions to 16. As only TimeStamp is required from firestore, thats my import statement: 

`import {Timestamp} from "firebase-admin/firestore";`

Below is my package.json

```{
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "watch": "tsc --watch",
    "serve": "firebase emulators:start",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^11.5.0",
    "firebase-functions": "^4.2.1",
    "google-auth-library": "^8.7.0",
    "googleapis": "^114.0.0",
    "lodash": "^4.17.21",
    "node-apple-receipt-verify": "^1.12.1",
    "camelcase-keys": "8.0.2"
  },
  "devDependencies": {
    "@types/node": "^18.15.11",
    "@types/node-apple-receipt-verify": "^1.7.1",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "eslint": "^8.37.0",
    "eslint-config-google": "^0.14.0",
    "eslint-import-resolver-typescript": "^3.5.5",
    "eslint-plugin-import": "^2.27.5",
    "firebase-functions-test": "^3.0.0",
    "typescript": "^5.0.3"
  },
  "private": true
}
```

Also I'm using `eslint-import-resolver-typescript` with following configuration inside `.eslintrc.js`
```
module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
    "google",
    "plugin:@typescript-eslint/recommended",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: ["tsconfig.json", "tsconfig.dev.json"],
    sourceType: "module",
  },
  ignorePatterns: [
    "/lib/**/*", // Ignore built files.
  ],
  plugins: [
    "@typescript-eslint",
    "import",
  ],
  rules: {
    "quotes": ["error", "double"],
    "require-jsdoc": "off",
    "max-len": ["error", {"ignoreStrings": true, "ignoreTemplateLiterals": true}],
    "no-invalid-this": "off",
  },
  settings: {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"],
    },
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true, // always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
        "project": "./tsconfig.json",
      },
    },
  },
};
```

Maybe this helps keep everything up to date.

**Comment by miquelbeltran** [comment]
I think we should close this PR, as we are currently moving away from the js/firebase based solution to a Dart one.

@domesticmouse what do you think?

**Comment by simonpham** [comment]
> I think we should close this PR, as we are currently moving away from the js/firebase based solution to a Dart one.
> 
> @domesticmouse what do you think?

It's OK to move to a new approach, but the old one should be working. You just need to stop merging PRs from dependency bots which broke things, not this one or any PR which fixes that.

**Comment by domesticmouse** [comment]
I believe this is now no longer required with the migration of the in app purchases backend to Dart

**Pull request closed without merging**
