### PR TITLE
Add code for the testing codelab

### PR DESCRIPTION
**Pull request by abd99**
@domesticmouse, please let me know if something needs to be changed.

@sfshaza2, I noticed that the [contributing guide](https://github.com/flutter/codelabs/blob/master/CONTRIBUTING.md) says that all the files should contain a copyright header that goes `Copyright 2018 The Chromium Authors...`, whereas every file in the repo actually follows `Copyright 2020 The Flutter team...` I know that it's just a small thing, but I thought that I should bring it up.

### CODE REVIEW

**Comment by sfshaza2** [comment]
Thanks for reviewing this, @domesticmouse!

@abd99, my understanding is that the copyright notice only needs updating if the code is updated.

**Comment by abd99** [comment]
> @abd99, my understanding is that the copyright notice only needs updating if the code is updated.

@sfshaza2 I'm sorry if I wasn't able to describe it correctly, I meant that all the files mention `The Flutter team` whereas in the contributing guide it mentions `The Chromium Authors`. I know that the year isn't supposed to be updated. =)
I think we need to update the [contributing guide](https://github.com/flutter/codelabs/blob/master/CONTRIBUTING.md).

**Comment by domesticmouse** [comment]
@RedBrogdon I suspect the Travis testing script doesn't like the way I have asked @abd99 to set up this codelab. Can you have a look and confirm one way or the other.

**Comment by abd99** [comment]
@domesticmouse the Travis script is recreating the project files and causing the tests to fail.

**Comment by abd99** [comment]
PTAL @domesticmouse, the build is passing now. Let me know if anything else needs to be changed/added.

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
