### PR TITLE
Rebuild tfserving Flutter apps

### PR DESCRIPTION
**Pull request by domesticmouse**
Rebuild the Flutter apps with latest stable version of Flutter, including runners for Desktop.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @windmaple

**Comment by windmaple** [comment]
Is the broken CI on Mac due to M1 compatibility?

**Comment by domesticmouse** [comment]
The issue with the beta CI macOS failure is under investigation. The initial suspicion was M1 requiring the addition of Rosetta to the CI image, but https://github.com/flutter/codelabs/pull/387 shows that isn't the required fix.

**Comment by windmaple** [comment]
LGTM

**Review by RedBrogdon — APPROVED** [review]

**Pull request merged**
