### PR TITLE
Update drag_and_drop.dart

### PR DESCRIPTION
**Pull request by Piinks**
This updates the drag and drop codelab  to migrate it away from deprecated code.

Fixes https://github.com/flutter/flutter/issues/80552

### CODE REVIEW

**Comment by domesticmouse** [comment]
Hey @Piinks!

Thanks for the PR, but it looks like our [CI bots are still upset](https://github.com/flutter/codelabs/pull/92/checks?check_run_id=2366350385#step:7:42). Can you help them feel betterer?

```
  error • The named parameter 'dragAnchorStrategy' isn't defined • lib/examples/drag_and_drop.dart:144:7 • undefined_named_parameter
  error • Undefined name 'pointerDragAnchorStrategy' • lib/examples/drag_and_drop.dart:144:27 • undefined_identifier
```

**Comment by domesticmouse** [comment]
(I'm guessing we need to drop the Cookbook from the `beta` and `dev` testing stream and hold this PR until Flutter 2.2 goes stable)

**Comment by Piinks** [comment]
> Hey @Piinks!
> 
> Thanks for the PR, but it looks like our [CI bots are still upset](https://github.com/flutter/codelabs/pull/92/checks?check_run_id=2366350385#step:7:42). Can you help them feel betterer?
> 
> ```
>   error • The named parameter 'dragAnchorStrategy' isn't defined • lib/examples/drag_and_drop.dart:144:7 • undefined_named_parameter
>   error • Undefined name 'pointerDragAnchorStrategy' • lib/examples/drag_and_drop.dart:144:27 • undefined_identifier
> ```

I was curious if this would work, it looks like we won't be able to migrate yet since this change has not reached any of the release branches yet. I'll keep an eye on it, but I am guessing we have to wait for it to reach stable. :)

**Comment by domesticmouse** [comment]
Temporary workaround: https://github.com/flutter/codelabs/pull/93

**Comment by Piinks** [comment]
I am going to close this as it cannot land until a stable release. As I understand it, updates like this are something that is typically done as part of the release process.

**Comment by domesticmouse** [comment]
Hey @Piinks I'm happy to have this open, waiting to land. It's better to get everything reviewed and signed off well in advance of when it needs to land.

**Comment by domesticmouse** [comment]
TODO(domesticmouse): Land when next Flutter stable lands.

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
