### PR TITLE
Cache `FragmentProgram`s not `FragmentShader`s

### PR DESCRIPTION
**Pull request by domesticmouse**
This works for macOS, but fails for web with the following error:

```console
Rejecting promise with error: Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'
_js_helper.TypeErrorImpl.new
```

Any ideas?

Context: https://github.com/flutter/flutter/issues/125079

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
@kevmoo i can't see how I'm breaking the web here. The error message is from the latest beta.

**Review by jonahwilliams — APPROVED** [review]
Shader change LGTM

**Comment by domesticmouse** [comment]
> @kevmoo i can't see how I'm breaking the web here. The error message is from the latest beta.

Probably related: https://github.com/flutter/flutter/issues/123794

**Comment by kevmoo** [comment]
Did you figure it out? I don't know much here.

**Comment by domesticmouse** [comment]
> Did you figure it out? I don't know much here.

I'll poke it tomorrow after I've slept

**Pull request merged**
