### PR TITLE
Add missing onTap

### PR DESCRIPTION
**Pull request by koenigscode**
Added missing onTap as shown on the codelab site at https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/index.html?index=..%2F..index#4

### CODE REVIEW

**Comment by OlivierJM** [comment]
When is this getting merged, As I was following the tutorial after adding the onTap as indicated it only refreshes the list instead of saving to favourites, everything looks good so far.
Anyway, it would be good if this was merged because it confuses new people.

**Comment by atapas** [comment]
> When is this getting merged? As I was following the tutorial after adding the onTap as indicated it only refreshes the list instead of saving to favourites, everything looks good so far.
> 
> Though not so related, It would be good if this was merged because it confuses new people.

I am facing the same issue. The Code I have followed here is not working as expected:
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#4

**Comment by jmazin** [comment]
it's also present in step 5 (though don't think it's supposed to be)! 😃

**Comment by sfshaza2** [comment]
LGTM

**Pull request merged**
