### PR TITLE
Flame codelab cleanup

### PR DESCRIPTION
**Pull request by khanhnwin**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. For larger changes, raising an issue first helps
reduce redundant work.*

## Pre-launch Checklist

- [ ] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
CI isn't liking these changes. Halp?

**Comment by khanhnwin** [comment]
Will add ignore_for_file tags once I've fully cleaned up all the files!

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
> Will add ignore_for_file tags once I've fully cleaned up all the files!

Please don't use `ignore_for_file`. Either fix the code or introduce the drop analysis rule in the project wide configuration

**Comment by khanhnwin** [comment]
> > Will add ignore_for_file tags once I've fully cleaned up all the files!
> 
> Please don't use `ignore_for_file`. Either fix the code or introduce the drop analysis rule in the project wide configuration

Yes! I did realize that adding an analysis_options.yaml file that disabled specific rules at the root of the flame codelab directory made more sense. That's been added as part of the PR!

**Pull request merged**
