### PR TITLE
`next-gen-ui`: Use records

### PR DESCRIPTION
**Pull request by domesticmouse**
Fixes https://github.com/flutter/flutter/issues/123949

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by kevmoo** [comment]
Gotta wait for beta to get updated.
It'd be nice of the boilerplate updates were done in a separate PR

**Comment by domesticmouse** [comment]
> Gotta wait for beta to get updated. It'd be nice of the boilerplate updates were done in a separate PR

This is good to land now. I'm building a separate PR with boilerplate updates, but there are some issues that I'm still working through.

**Review by kevmoo — APPROVED** [review]
I wish the ios/android bits were separate. But I'll live...

**Comment by domesticmouse** [comment]
> I wish the ios/android bits were separate. But I'll live...

=)

**Pull request merged**
