### PR TITLE
Run analysis and format on stable, beta and dev

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
Hey @matthew-carroll, any chance of some guidance on the `cookbook` codelab? It looks like I have an issue after `2.3.0-0.1.pre`:

```
== TESTING cookbook
+ flutter analyze
Running "flutter pub get" in cookbook...                         2,399ms
Analyzing cookbook...                                           

   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. This feature was deprecated after v2.3.0-0.1.pre. • lib/app.dart:32:9 • deprecated_member_use
   info • 'accentColor' is deprecated and shouldn't be used. Use colorScheme.secondary instead. This feature was deprecated after v2.3.0-0.1.pre. • lib/examples/expandable_fab.dart:271:20 • deprecated_member_use
   info • 'accentIconTheme' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. This feature was deprecated after v2.3.0-0.1.pre. • lib/examples/expandable_fab.dart:274:21 • deprecated_member_use
   info • Sort directive sections alphabetically • lib/items.dart:13:1 • directives_ordering

4 issues found. (ran in 14.3s)
```

**Comment by matthew-carroll** [comment]
@domesticmouse is there a specific question that I can answer? It looks like this PR just changes some run configurations for an add-to-app example...

**Comment by domesticmouse** [comment]
@matthew-carroll I was wondering if you had preferences on how I migrate your codelab, given it has deprecated usage of `accentColor` and `accentIconTheme`. Thanks!

**Comment by domesticmouse** [comment]
After chatting with @RedBrogdon, I'm going to drop `cookbook` from Dev CI until the accent changes make it closer to stable.

**Comment by domesticmouse** [comment]
TBR: @RedBrogdon

**Comment by domesticmouse** [comment]
Heads up @sfshaza2, I expect this PR will cause issues with flutter.dev's build pipeline. What do I need to do to rectify?

**Comment by sfshaza2** [comment]
It seems ok, yes?

**Comment by sfshaza2** [comment]
Btw, @matthew-carroll no longer works for Google.

**Comment by domesticmouse** [comment]
@sfshaza2 I was guessing that the changes this PR does to various imports would impact some of the codelabs on Flutter.dev. If this is not the case, sweet =)

**Pull request merged**
