### PR TITLE
Fix audio_soloud codelab

### PR DESCRIPTION
**Pull request by filiph**
Fixes and reenables CI for `audio_soloud`. Updates the minimum iOS and macOS deployment target to what `pkg:flutter_soloud` needs.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please fix up deprecated warnings:

```console
info - lib/audio/audio_controller.dart:67:14 - 'addGlobalFilter' is deprecated and shouldn't be used. Please, to manage global filters use SoLoud.filters instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

**Review by domesticmouse — CHANGES_REQUESTED** [review]
Please fix CI warnings

**Comment by filiph** [comment]
On it. I needed to fix another (runtime) issue in parallel, but all looks good now (after the codelab_build run finishes, fingers crossed). 

Marco (@alnitak) and I also updated the codelab text: https://docs.google.com/document/d/1PZbGEXGbXUVsIpEMsSKMR_7b8ok5Gyl-fqFPmqOy_8w/edit

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
> On it. I needed to fix another (runtime) issue in parallel, but all looks good now (after the codelab_build run finishes, fingers crossed).
> 
> Marco (@alnitak) and I also updated the codelab text: https://docs.google.com/document/d/1PZbGEXGbXUVsIpEMsSKMR_7b8ok5Gyl-fqFPmqOy_8w/edit

For googlers, please see cl/687449390

**Pull request merged**
