### PR TITLE
FFI codelab, take two

### PR DESCRIPTION
**Pull request by domesticmouse**
A second attempt at populating the code files for the FFI codelab.

PTAL @maks 

Note for reviewers: The `ffi_codelab/codelab_rebuild.yaml` file is worth reviewing as it is the script that is used to generate the various steps of the codelab. 

Some additional functionality was required to be added to the `codelab_rebuild` tool for this script. This is the way.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by maks** [comment]
@domesticmouse I had a quick look and mostly looks good but `step_05` seems to be missing the sources for the msfa native lib that I previously had in `libmsfa` top level directory.

**Comment by domesticmouse** [comment]
> @domesticmouse I had a quick look and mostly looks good but `step_05` seems to be missing the sources for the msfa native lib that I previously had in `libmsfa` top level directory.

The `libmsfa` source code wasn't part of your original PR, so I had it `.gitignore`'d. I've removed the `.gitignore` and added most of the files in. Dropped the GitHub workflows, as I'm guessing they aren't required.

**Comment by maks** [comment]
@domesticmouse great stuff, I tested step 5 and complete on desktop Linux and both working fine now 👍🏻

**Comment by domesticmouse** [comment]
I have it confirmed working on macOS, iOS, Android and Linux. Next up Windows, and figuring out a sane configuration for LLVM on all platforms. Ick

**Comment by domesticmouse** [comment]
Actually windows is breaking on compiling the example app. Let me know if you can spot my mistake

**Comment by domesticmouse** [comment]
@maks here's what I'm seeing when I attempt to compile on windows with `--verbose`

```console
[   +1 ms] Build FAILED.
[   +1 ms] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\INSTALL.vcxproj" (default target) (1) ->
[        ] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msfa_plugin.vcxproj" (default target)  
(7) ->
[   +1 ms] (ClCompile target) ->
[        ]   cl : command line error D8021: invalid numeric argument '/Wno-c++11-narrowing'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msfa_plugin.vcxproj]
[   +1 ms]     0 Warning(s)
[   +1 ms]     1 Error(s)
[   +1 ms] Time Elapsed 00:00:12.70
[  +39 ms] Building Windows application... (completed in 13.7s)
```

Halp?

**Comment by maks** [comment]
@domesticmouse hmm actually according to this SO: https://stackoverflow.com/a/56666272/85472 VisualStudio doesn't even have that compiler check, so I think need we'd need to change that line in CMake to not apply for windows using [something like this](https://stackoverflow.com/a/9160449/85472) 

```
if (MSVC)
    # do something
endif (MSVC)
```

**Comment by domesticmouse** [comment]
@maks new set of failures:

```console
[  +27 ms] Project
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\ALL_BUILD.vcxproj" (3) is     
building
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj" (7) on node 1 (default targets).
[   +1 ms] InitializeBuildStatus:
[        ]   Touching "msfa_plugin.dir\Debug\msfa_plugin.tlog\unsuccessfulbuild".
[   +2 ms] CustomBuild:
[   +1 ms]   All outputs are up-to-date.
[  +39 ms]   Building Custom Rule
C:/Users/brett/Documents/GitHub/codelabs/ffi_codelab/complete/example/windows/flutter/ephemeral/.plugin_symlinks/ms
fa_plugin/src/CMakeLists.txt
[  +62 ms] ClCompile:
[   +1 ms]   C:\Program Files\Microsoft Visual
Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\CL.exe /c
/IC:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\
msfa_plugin\src\include /Zi /nologo /W1 /WX- /diagnostics:column /Od /Ob0 /D _WINDLL /D _UNICODE /D UNICODE /D     
UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /D msfa_plugin_EXPORTS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t 
/Zc:forScope /Zc:inline /Fo"msfa_plugin.dir\Debug\\" /Fd"msfa_plugin.dir\Debug\vc143.pdb" /external:W1 /Gd /TP     
/errorReport:queue  -pthread
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\dx7note.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\env.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\exp2.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\fir.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\fm_core.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\fm_op_kernel.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\freqlut.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\lfo.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\log2.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\libmsfa.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\patch.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\pitchenv.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\resofilter.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\ringbuffer.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\sawtooth.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\sin.cc
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth_unit.cc
[  +86 ms] cl : command line warning D9002: ignoring unknown option '-pthread'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]   dx7note.cc
[   +9 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[ +173 ms]   env.cc
[  +47 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +5 ms]   exp2.cc
[ +122 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +8 ms]   fir.cc
[  +88 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\fir.cc(32,16): error C3861: 'posix_memalign': identifier not found
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +6 ms]   fm_core.cc
[  +32 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +3 ms]   fm_op_kernel.cc
[  +40 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +4 ms]   freqlut.cc
[  +41 ms]   lfo.cc
[  +23 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +5 ms]   log2.cc
[  +39 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +3 ms]   libmsfa.cc
[ +267 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +5 ms]   patch.cc
[  +38 ms]   pitchenv.cc
[  +23 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +3 ms]   resofilter.cc
[  +66 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +4 ms]   ringbuffer.cc
[  +44 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +3 ms]   sawtooth.cc
[  +34 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\sawtooth.cc(71,31): error C2065: 'M_PI': undeclared identifier
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +4 ms]   sin.cc
[  +32 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +3 ms]   synth_unit.cc
[  +35 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +3 ms]   Generating Code...
[  +71 ms] Done Building Project
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj" (default targets) -- FAILED.
[  +32 ms] Project
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\ALL_BUILD.vcxproj" (3) is     
building
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\runner\msfa_plugin_example.vcx
proj" (8) on node 1 (default targets).
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "msfa_plugin_example.dir\Debug\msfa_plu.4DD7FFD4.tlog\unsuccessfulbuild" because
"AlwaysCreate" was specified.
[   +1 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +30 ms] ClCompile:
[        ]   C:\Program Files\Microsoft Visual
Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\CL.exe /c
/IC:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows
/IC:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral
/IC:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\cpp_client_wrappe
r\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D
_HAS_EXCEPTIONS=0 /D _DEBUG /D "FLUTTER_VERSION=\"1.0.0+1\"" /D FLUTTER_VERSION_MAJOR=1 /D FLUTTER_VERSION_MINOR=0 
/D FLUTTER_VERSION_PATCH=0 /D FLUTTER_VERSION_BUILD=1 /D NOMINMAX /D UNICODE /D _UNICODE /D
"CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17  
/Fo"msfa_plugin_example.dir\Debug\\" /Fd"msfa_plugin_example.dir\Debug\vc143.pdb" /external:W4 /Gd /TP /wd4100     
/errorReport:queue
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\generated_plugin_registrant.c
c C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\runner\flutter_window.cpp
[  +45 ms]   generated_plugin_registrant.cc
[ +271 ms]   flutter_window.cpp
[ +938 ms]   Generating Code...
[ +146 ms] ResourceCompile:
[        ]   All outputs are up-to-date.
[  +47 ms] Link:
[        ]   C:\Program Files\Microsoft Visual
Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE
/OUT:"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\runner\Debug\msfa_plugin_
example.exe" /INCREMENTAL /ILK:"msfa_plugin_example.dir\Debug\msfa_plugin_example.ilk" /NOLOGO
..\flutter\Debug\flutter_wrapper_app.lib
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\flutter_windows.dll
.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib       
advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed
/manifestinput:C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\runner\runner.exe.mani
fest /DEBUG
/PDB:"C:/Users/brett/Documents/GitHub/codelabs/ffi_codelab/complete/example/build/windows/runner/Debug/msfa_plugin_
example.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT
/IMPLIB:"C:/Users/brett/Documents/GitHub/codelabs/ffi_codelab/complete/example/build/windows/runner/Debug/msfa_plug
in_example.lib" /MACHINE:X64  /machine:x64 msfa_plugin_example.dir\Debug\Runner.res
[   +3 ms]   msfa_plugin_example.dir\Debug\flutter_window.obj
[        ]   msfa_plugin_example.dir\Debug\main.obj
[   +1 ms]   msfa_plugin_example.dir\Debug\utils.obj
[   +1 ms]   msfa_plugin_example.dir\Debug\win32_window.obj
[   +2 ms]   msfa_plugin_example.dir\Debug\generated_plugin_registrant.obj
[ +193 ms]   msfa_plugin_example.vcxproj ->
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\runner\Debug\msfa_plugin_exampl
e.exe
[   +7 ms] FinalizeBuildStatus:
[        ]   Deleting file "msfa_plugin_example.dir\Debug\msfa_plu.4DD7FFD4.tlog\unsuccessfulbuild".
[        ]   Touching "msfa_plugin_example.dir\Debug\msfa_plu.4DD7FFD4.tlog\msfa_plugin_example.lastbuildstate".   
[        ] Done Building Project
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\runner\msfa_plugin_example.vcx
proj" (default targets).
[        ] Done Building Project
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\ALL_BUILD.vcxproj" (default   
targets) -- FAILED.
[   +1 ms] Done Building Project
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\INSTALL.vcxproj" (default     
targets) -- FAILED.
[   +1 ms] Build FAILED.
[        ] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\INSTALL.vcxproj"   
(default target) (1) ->
[        ] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\ALL_BUILD.vcxproj" 
(default target) (3) ->
[        ]
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj" (default target) (7) ->
[        ] (ClCompile target) ->
[        ]   cl : command line warning D9002: ignoring unknown option '-pthread'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[        ] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\INSTALL.vcxproj"   
(default target) (1) ->
[        ] "C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\ALL_BUILD.vcxproj"
(default target) (3) ->
[        ]
"C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj" (default target) (7) ->
[        ] (ClCompile target) ->
[        ]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\fir.cc(32,16): error C3861: 'posix_memalign': identifier not found
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
fa_plugin\src\libmsfa\src\synth.h(40,1): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\build\windows\plugins\msfa_plugin\shared\msf
a_plugin.vcxproj]
[   +1 ms]
C:\Users\brett\Documents\GitHub\codelabs\ffi_codelab\complete\example\windows\flutter\ephemeral\.plugin_symlinks\ms
[   +3 ms] Exception: Build process failed.
[   +6 ms] "flutter run" took 15,528ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +119 ms] ensureAnalyticsSent: 115ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by domesticmouse** [comment]
Ima gunna need another library...

**Pull request closed without merging**
