### PR TITLE
[forge2d codelab] Use flame_kenney_xml instead of manual XML parsing

### PR DESCRIPTION
**Pull request by spydon**
This simplifies the forge2d codelab by using the flame_kenney_xml package (official Flame package) for parsing the Kenney sprite sheets. (It pretty much contains the same code as @domesticmouse previously wrote for this codelab)

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Comment by spydon** [comment]
Oh, it seems like it bumped some dependencies when running `codelab_rebuild` too.

**Comment by spydon** [comment]
The diffs are not correct, I should have just edited the files and getting the diffs instead of directly editing the `code_rebuild.yaml` :sweat_smile:

**Comment by domesticmouse** [comment]
Thank you for this PR @spydon! 

I doubt I'm going to have time to update the codelab text and [`domesticmouse/forge2d_workshop_presentation`](https://github.com/domesticmouse/forge2d_workshop_presentation) before I/O Connect Bengaluru. See how the next couple of weeks go.

**Comment by spydon** [comment]
> Thank you for this PR @spydon! 
> 
> I doubt I'm going to have time to update the codelab text and [`domesticmouse/forge2d_workshop_presentation`](https://github.com/domesticmouse/forge2d_workshop_presentation) before I/O Connect Bengaluru. See how the next couple of weeks go.

Thanks a lot for fixing it up!
I was a bit too busy now with I/O Connect Berlin and FlutterCon.

I might be able to help with the text once I'm back from Berlin. :)

**Review by domesticmouse — APPROVED** [review]
I'll land once the codelab text and presentation app have also been updated.

**Comment by domesticmouse** [comment]
I think I've updated the codelab text. Just waiting on @RedBrogdon to sign off the updated codelab for publication before landing this PR.

**Pull request merged**
