### PR TITLE
enable material3 in this app

### PR DESCRIPTION
**Pull request by AdamMusa**
Enable material 3 in this app

**Here is some screenshot before enabling material 3**

before
before_1
before_ios
before_ios_1

**Here is some screenshot after enabling material 3**

after
after_1
after_ios
after_ios_1

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Thanks @AdamMusa 

Can you share a screenshot of the app with Material 3 enabled? It is to verify that the Material 3 UI and color look correct.

**Comment by AdamMusa** [comment]
> Thanks @AdamMusa
> 
> Can you share a screenshot of the app with Material 3 enabled? It is to verify that the Material 3 UI and color look correct.
Ok no problem I'll do in a few minutes

**Comment by domesticmouse** [comment]
I'm curious why the "Generate haiku!" button hasn't adopted the theme color. I'm guessing it is hard coded to blue?

Also, before landing a change to the haiku codelab, we should get @windmaple's review =)

**Comment by miquelbeltran** [comment]
The button is implemented using a `Container`, not a `FilledButton`. I'll recommend using that instead of a `Container` + `GestureDetector`. Maybe should be done in this PR as well?

**Comment by AdamMusa** [comment]
Hello @miquelbeltran I already implemented with FIlledButton I can passe  backgroundColor: Colors.blue or I leave without passing this attribute ?

**Comment by AdamMusa** [comment]
Here is the new screenshot after enabling m3 and reimplemented **Container+GestureDetector** by **FilledButton**
after

**Comment by miquelbeltran** [comment]
Thansk @AdamMusa a couple of comments:

- I'd remove the custom style and instead use the default style for the FilledButton.
- I'd revert all changes unrelated (e.g. changes in the android and ios project files)

**Comment by AdamMusa** [comment]
> Thansk @AdamMusa a couple of comments:
> 
> * I'd remove the custom style and instead use the default style for the FilledButton.
> * I'd revert all changes unrelated (e.g. changes in the android and ios project files)

Ok , it sounds good .

**Comment by domesticmouse** [comment]
@AdamMusa are you intending on implementing @miquelbeltran's suggestions? =)

@windmaple can you take a look please?

**Comment by windmaple** [comment]
LGTM

**Comment by domesticmouse** [comment]
PTAL @miquelbeltran, I've implemented your suggested changes (I hope)

**Comment by domesticmouse** [comment]
Updated screenshot:

Screenshot 2023-07-24 at 10 01 24 am

**Review by miquelbeltran — APPROVED** [review]
Thanks!

**Comment by domesticmouse** [comment]
Thanks @AdamMusa and @miquelbeltran!

**Pull request merged**
