### PR TITLE
[photos-sharing] Expand use of nullability for API calls and parameters.

### PR DESCRIPTION
**Pull request by jfschmakeit**

### CODE REVIEW

**Comment by jfschmakeit** [comment]
This pull request also requires some changes to the codelab document - I'll reach out about those separately as part of switching over the instructions to this repository.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
@jfschmakeit let me know when you want me to land this PR

**Comment by jfschmakeit** [comment]
@domesticmouse We should be good to squash/merge this in once the CI pass. I'll do another request to clean up the README once we are all good to switch over to this version.

**Comment by domesticmouse** [comment]
Thanks JF!

**Pull request merged**
