### PR TITLE
`testing_codelab` update

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
@miquelbeltran Are you ok for me to add this to your work queue? Your plan sounds like a great plan to me!

**Comment by miquelbeltran** [comment]
> @miquelbeltran Are you ok for me to add this to your work queue? Your plan sounds like a great plan to me!

yep, no problem!

**Comment by miquelbeltran** [comment]
There are some classes that have been moved, so they no longer match what's in the codelab_rebuild. 

I will go through it and let you know.

**Comment by miquelbeltran** [comment]
Changes that should be made:

- Step 06:
  - `integration_test` folder does not belong to this step.
- Step 07:
  - do not create the `integration_test/driver.dart` file
- Step 08:
  - missing, it adds the `test_driver/perf_driver.dart` and `integration_test/perf_test.dart` files

**Pull request closed without merging**
