### PR TITLE
firebase-get-to-know-flutter: separate main.dart into different files

### PR DESCRIPTION
**Pull request by miquelbeltran**
As preparation for migrating the codelab to go_router (and Material 3 later on)

Work is mostly copy/paste and re-formatting, changes are organized in commit per step for easier review.

Final code organization is as follows:

image

The only doubt I had was if the `Attending` `enum` should be a separated file or not, since it was only used by the `ApplicationState`, I left it inside `app_state.dart`

I did not update the `codelab_rebuild.yaml` as I am still not sure how to do that, but I can give it a try if you let me know how.

We would need to update the codelab document as well. I can do that after go_router has been adopted, or I can do that now before migrating to go_router. Please let me know what you prefer.

cc. @domesticmouse @nohe427 @RedBrogdon 

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`). <-- Codelab needs update
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by nohe427** [comment]
Yes, @miquelbeltran - Please add license headers

**Comment by nohe427** [comment]
I think the codelab.md might be out of sync with what is published on the site. I can land an update to that momentarily.

**Review by nohe427 — COMMENTED** [review]
LGTM

**Review by domesticmouse — APPROVED** [review]

**Comment by miquelbeltran** [comment]
Added license headers. I skipped the `firebase_options.dart` file since it is generated by the FlutterFire CLI.

**Review by domesticmouse — APPROVED** [review]
Free to land when tests pass

**Pull request merged**
