### PR TITLE
enable Material 3 on adaptive_app codelab code

### PR DESCRIPTION
**Pull request by miquelbeltran**
Part of the work to enable Material 3 on all codelabs and samples.

Initial work done by setting `useMaterial3: true` on the ThemeData creation.

Further work needs to be done, updating the codelab code and screenshots. I already have access to the Adaptive App's Flutter codelab doc, so I can update it once this PR is approved.

### Before Material 3

image

image

image

### With Material 3

image

image

image

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`). <-- pending
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @khanhnwin

**Comment by domesticmouse** [comment]
@miquelbeltran Can you please grab screenshots of the app before and after? It'll make it easier for @khanhnwin to judge if there are any UX breakages we need to dive into

**Comment by miquelbeltran** [comment]
Yep, I will do that

**Comment by miquelbeltran** [comment]
@domesticmouse @khanhnwin the PR description has been updated with the screenshots

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Next step, update the codelab content =)

**Pull request merged**
