### PR TITLE
chore: Updated the "Getting started" step 4

### PR DESCRIPTION
**Pull request by albertodev01**
This is a follow-up for the update to the "Getting started" codelab in [this](https://github.com/flutter/website/pull/6671) PR.

I am making sure that helper methods aren't used but instead actual widgets are.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by domesticmouse** [comment]
In updating step 4, you'll need to update all the following steps as well

**Review by domesticmouse — CHANGES_REQUESTED** [review]
Update follow on steps

**Comment by albertodev01** [comment]
Thank you @domesticmouse for your review, I've updated the following steps too

**Comment by domesticmouse** [comment]
Before I can merge this I'll need to re-write all three codelabs to use the new code snippets

**Comment by domesticmouse** [comment]
I'm curious about this failure:

```
== Testing 'startup_namer/step4_infinite_list'
Analyzing step4_infinite_list...

  error - lib/main.dart:57:8 - Expected to find ')'. - expected_token

1 issue found.
```

Also, please update the PR to merge in a break fix.

**Comment by albertodev01** [comment]
I fixed it @domesticmouse

**Comment by domesticmouse** [comment]
Still showing red in CI: https://github.com/flutter/codelabs/runs/4845560924?check_suite_focus=true#step:7:1430

**Comment by albertodev01** [comment]
@domesticmouse I've run all of them one by one in my machine and they all run on Web & mobile so we should be ok now

**Comment by domesticmouse** [comment]
@albertodev01 re-running CI. Once this PR lands you will get CI automatically on future PRs.

**Comment by albertodev01** [comment]
@domesticmouse thank you! I see it failing again, is that because you require `flutter format .` to be run before pushing?

**Comment by domesticmouse** [comment]
Dart format is required =)

**Comment by albertodev01** [comment]
@domesticmouse it seems that the CI action is not automatically starting, I need your help!

**Comment by domesticmouse** [comment]
I'll need to re-auth CI flows on this PR as until this lands you haven't contributed to this repo yet. All good, just poke me as required!

**Comment by albertodev01** [comment]
@domesticmouse we've finally got it 😄 CI is now happy

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Thanks @albertodev01!

**Pull request merged**
