### PR TITLE
`webview_flutter`: Replace `print` with SnackBar

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by mvanbeusekom — APPROVED** [review]
LGTM! Thanks a lot for all this effort Brett. Please next time let us know and we will spend the time fixing it.

**Comment by domesticmouse** [comment]
I need to figure out a better way of being able to work with your team on the next codelab. 

I'm currently working on tooling to capture deltas and enable regeneration of codelabs for each new flutter stable release.

**Comment by mvanbeusekom** [comment]
In this case however, simply a message saying: "Please replace all print statements with a user friendly snackbar" would have saved you some work ;). However we are very great full of all your work.

**Comment by domesticmouse** [comment]
> In this case however, simply a message saying: "Please replace all print statements with a user friendly snackbar" would have saved you some work ;). However we are very great full of all your work.

There were a bunch of minor tidy ups to make the finished app tidier, e.g. menu item labels, returning response snack bars populated with user friendly messages, and eliminating the need for the build widget.

These tidy ups only happen after I do a codelab three or four times in a row. It takes a lot of polish to finish a codelab, aka the last ten percent of the project takes the other 90% of the project.

**Pull request merged**
