### PR TITLE
Fix addMessage's type

### PR DESCRIPTION
**Pull request by domesticmouse**
Partial fix of https://github.com/flutter/flutter/issues/69239

/cc @ToddKerpelman

### CODE REVIEW

**Comment by ToddKerpelman** [comment]
Drat, I just filmed the screencast where I worked around this -- no worries. I can add an annotation in the screencast. Good to know there's a FutureOr type, though.

**Comment by domesticmouse** [comment]
Sorry Todd! Next time you hit an issue like this, hold my feet to the fire.

**Comment by ToddKerpelman** [comment]
Oh, don't worry about it. These things happen all the time.

**Comment by domesticmouse** [comment]
Holiday =)

**Pull request merged**
