### PR TITLE
Update for Flutter 3.3.2

### PR DESCRIPTION
**Pull request by domesticmouse**
This is in preparation for a new Flutter beta cut.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by RedBrogdon** [comment]
Is it expected for the beta tests to be failing, or should I hold off on review?

**Comment by domesticmouse** [comment]
> Is it expected for the beta tests to be failing, or should I hold off on review?

Beta will fail until a post Flutter 3.3 beta is cut, which should happen soon. Feel free to hold off reviewing until the new beta lands.

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon this is now ready to land

**Review by parlough — APPROVED** [review]
Updates and changes look good to me.

**Pull request merged**
