### PR TITLE
Update codelab to use Firebase UI.

### PR DESCRIPTION
**Pull request by nohe427**
This PR updates the codelab to use firebase ui so its easier for developers to adopt fully features UIs.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by nohe427** [comment]
FYI, the tests will probably fail because we don't have a firebase project setup here.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
> FYI, the tests will probably fail because we don't have a firebase project setup here.

Please modify the tests so they pass on CI. I won't land it while it is red.

**Comment by domesticmouse** [comment]
Please pull latest from master, but it should be good to land. Let me know when you want me to hit the merge button.

**Comment by nohe427** [comment]
Awesome! I just pulled main into my branch. I'm good to go when you are

**Pull request merged**
