### PR TITLE
Make `animations` maintainable

### PR DESCRIPTION
**Pull request by domesticmouse**
Land with cl/699849063

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Comment by johnpryan** [comment]
Oops, I didn't realize this wasn't maintainable, do we have any resources to help avoid mistakes in the future?

**Comment by domesticmouse** [comment]
The pattern you adopted makes total sense for development. I'm moving things around to make it easier for me to update all the codelabs during the Dart 3.7 reformat.

I'm just happy you found a way to build this codelab out on the tight timeline that you did.

**Comment by domesticmouse** [comment]
Googlers: This PR matches cl/699849063

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Review by parlough — APPROVED** [review]

**Pull request merged**
