### PR TITLE
Transfer commit

### PR DESCRIPTION
**Pull request by itsjatinnagar**
commit 9ed03efa1d81b3e08bb18fc09da4200fb2fa6bf2
Author: itsjatinnagar <85210352+itsjatinnagar@users.noreply.github.com>
Date:   Mon Oct 4 17:02:18 2021 +0530
Message: issue solved using appbartheme (#189)

I have pushed this commit through my account with name "Jatin Nagar" and username "itsjatinnagar".
Now due to some reasons I have deleted that account and want to transfer the authorship of the commit to my new account.
Also, I want @domesticmouse to be assigned for this Pull Request because he is mentoring me during the time.

Thanks and regards

### CODE REVIEW

**Comment by domesticmouse** [comment]
> Also, I want @domesticmouse to be assigned for this Pull Request because he is mentoring me during the time.

I am?

Btw, this PR is sixty odd commits behind master. Please update and resolve conflicts.

**Review by domesticmouse — CHANGES_REQUESTED** [review]
Please bring this PR up to date

**Comment by domesticmouse** [comment]
Now that this PR has been brought up to date there are no outstanding changes. What were you attempting to do here?

**Review by domesticmouse — APPROVED** [review]

**Comment by itsjatinnagar** [comment]
> What were you attempting to do here?

I want my commit from previous account to show my new account.

**Comment by domesticmouse** [comment]
We land changes as merger commits. I'm not rewriting commit history, for reasonably obvious CLA reasons.

**Pull request closed without merging**
