### PR TITLE
Tidy up `dart-patterns-and-records`

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by miquelbeltran — APPROVED** [review]

**Review by miquelbeltran — APPROVED** [review]

**Comment by miquelbeltran** [comment]
LGTM. Thanks for separating the process in different commits, that helped with the review!

**Comment by domesticmouse** [comment]
> LGTM. Thanks for separating the process in different commits, that helped with the review!

Cool, I will continue to do that. It also helps with creating the PR =)

**Review by miquelbeltran — APPROVED** [review]
For what I can see, the only difference between Step 6 A and B is removing the first `modified` in the `modified:modified` assignment.

**Comment by domesticmouse** [comment]
> For what I can see, the only difference between Step 6 A and B is removing the first `modified` in the `modified:modified` assignment.

Yup, this is to properly stage `:modified` as a power user short cut for `modified:modified` akin to TypeScript I believe

**Pull request merged**
