### PR TITLE
Enable Material 3 on firebase-emulator-suite

### PR DESCRIPTION
**Pull request by miquelbeltran**
Enabled Material 3 on firebase-emulator-suite.

The class `MyApp` is not mentioned on the codelab https://firebase.google.com/codelabs/get-started-firebase-emulators-and-flutter#0, so there's no need to update the codelab document.

### Before Material 3

Screenshot 2023-01-10 at 15 01 49

Screenshot 2023-01-10 at 15 01 58

### With Material 3

Screenshot 2023-01-11 at 13 54 14

Screenshot 2023-01-11 at 13 54 25

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Description updated with screenshots

**Comment by miquelbeltran** [comment]
I switched to`FilledButton` for login and for submit

**Comment by domesticmouse** [comment]
This PR is trailing `main` by 62 commits. Please bring up to date.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by domesticmouse** [comment]
@miquelbeltran I'm thinking the purple theme and the blue background are clashing. Can we change one or the other?

**Comment by domesticmouse** [comment]
Please feel free to land once the clash is dealt with =)

**Comment by miquelbeltran** [comment]
Oops, sorry, I forgot about this

**Comment by miquelbeltran** [comment]
I think that simply removing the blue background color would be enough

image

**Pull request merged**
