### PR TITLE
Migrate in-app-purchases to Material 3

### PR DESCRIPTION
**Pull request by miquelbeltran**
Enabled Material 3 on the in-app-purchases codelab.

Replaced an `ElevatedButton` with a `FilledButton` on the Login screen.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by miquelbeltran** [comment]
@domesticmouse is it OK to merge even if it does not compile on Stable? or should I hold until next release?

**Comment by domesticmouse** [comment]
> @domesticmouse is it OK to merge even if it does not compile on Stable? or should I hold until next release?

Hold until stable increments. I could add this to the `beta` update PR if you want me to land this change.

**Comment by miquelbeltran** [comment]
I changed the base branch to `beta`.

In any case, we can decide tomorrow in the call.

**Comment by miquelbeltran** [comment]
Waiting for CI to finish and go green, then I'll merge.

**Pull request merged**
