### PR TITLE
Mistake in home page resolved #114619.

### PR DESCRIPTION
**Pull request by HaroonAwan**
Fixed Issue 114619
https://github.com/flutter/flutter/issues/114619

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

**Before** 
when you validate the state of logged in you try it with this condition
`if (appState.loginState == ApplicationLoginState.loggedIn) ...[ `
**After**
`      if (appState.loggedIn) ...[`

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please sign CLA. We cannot review this PR until the CLA is signed.

**Comment by HaroonAwan** [comment]
@domesticmouse Signed the CLA

**Comment by domesticmouse** [comment]
PTAL @nohe427

**Review by nohe427 — COMMENTED** [review]
LGTM 👍

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
@nohe427 I'll leave updating the published version to you. Feel free to cc me on the CL.

**Pull request merged**
