### PR TITLE
`ffigen_codelab`: Add `step_07`

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @maks 

Btw, you'll be amused to learn that the Duktape integration is breaking on Windows. I'm pretty certain I had it working, but I've got no idea how I broke it. Sigh.

**Comment by maks** [comment]
Looks great @domesticmouse ! Builds and runs fine on Ubuntu for me:

image

And looking at the last CI run looks like you solved the windows issue?

One small thing is that I think `src/CMakeLists.txt` has a typo on line 14?

**Comment by domesticmouse** [comment]
Nah, I haven't added tests. 😝

**Comment by domesticmouse** [comment]
@maks added a test and I have no idea how to make the test code load the library. Any ideas?

**Comment by maks** [comment]
@domesticmouse Hmm good question! I have an idea, let me have a quick go to see if it will work...

**Comment by maks** [comment]
@domesticmouse ok I got a quick unit test working here for me: https://github.com/maks/codelabs/commit/569fb6d33a1d5bbf0011887f8a01471e0584a6f0

using the tip from https://github.com/dart-lang/ffi/issues/39#issuecomment-681758550

My quick hack is only for Linux so it will need to be generalised for the diff paths if you want to test on all OS's.

I'm  also not sure why it doesn't seem to work for widget tests, but maybe for widget tests it would be better to not use the real native lib, ie. to have a riverpod provider for the native lib and then in the widgettests use a providerscope override to supply a fake provider?

**Comment by domesticmouse** [comment]
> @domesticmouse ok I got a quick unit test working here for me: https://github.com/maks/codelabs/commit/569fb6d33a1d5bbf0011887f8a01471e0584a6f0
> 
> 
> 
> using the tip from https://github.com/dart-lang/ffi/issues/39#issuecomment-681758550
> 
> 
> 
> My quick hack is only for Linux so it will need to be generalised for the diff paths if you want to test on all OS's.
> 
Thank you @maks 🤓
> 
> I'm  also not sure why it doesn't seem to work for widget tests, but maybe for widget tests it would be better to not use the real native lib, ie. to have a riverpod provider for the native lib and then in the widgettests use a providerscope override to supply a fake provider? 

For this codelab, testing the FFI is the point 😎

**Comment by maks** [comment]
> For this codelab, testing the FFI is the point sunglasses

Yes of course, sorry testing with the plugin in a Flutter widget test is the important part! 👍🏻 
I can see you spotted the issue with the widget test was just the string matching, doh! sorry I should have spotted that too.

**Comment by domesticmouse** [comment]
Inspecting the generated DLL files with [DLL Export Viewer](https://www.nirsoft.net/utils/dll_export_viewer.html), I'm seeing the DLL generated in Step 3 has appropriate exported entry points, yet the one in step 5 has nothing exported. I have vague recollections that windows requires something specific to export DLL entries?

**Comment by maks** [comment]
Hmmm @domesticmouse I would have expected the symbol export setting to come from CMake when it generates the VS build config?
That was the typo I mentioned in prev comment:
```
set_target_properties(ffigen_app PROPERTIES
  PUBLIC_HEADER duktape.h
  PRIVATE_HEADRE duk_config.h
  OUTPUT_NAME "ffigen_app"
)
```

**Comment by domesticmouse** [comment]
> Hmmm @domesticmouse I would have expected the symbol export setting to come from CMake when it generates the VS build config? That was the typo I mentioned in prev comment:
> 
> ```
> set_target_properties(ffigen_app PROPERTIES
>   PUBLIC_HEADER duktape.h
>   PRIVATE_HEADRE duk_config.h
>   OUTPUT_NAME "ffigen_app"
> )
> ```

Yup, I've corrected the `PRIVATE_HEADRE` gaffe, and added `WINDOWS_EXPORT_ALL_SYMBOLS` as well. Hopefully I will now have a DLL with exported symbols.

**Comment by domesticmouse** [comment]
Windows test passes locally. Now all I need to do is get the Linux CI environment configured correctly...

**Comment by domesticmouse** [comment]
Duktape REPL

**Comment by domesticmouse** [comment]
Status summary: 
 - Example is complete - JavaScript REPL and has been tested on Windows, macOS, Linux, iOS and Android.
 - Example includes minimal smoke test to prove library integration. Works locally on macOS, Windows, Linux
 - GitHub Action CI is passing the smoke test on macOS and Windows, but failing Linux
 - GitHub Action Linux CI can't run `flutter build linux --debug` which is required to build the Duktape C library.

**Comment by maks** [comment]
> @godofredoc Any ideas on how I can integrate the appropriate GitHub actions to install the required tooling to make compiling the Flutter linux app work?

sorry to butt in here @domesticmouse but could you perhaps add a script step that does `sudo apt install ninja-build` ?

**Comment by domesticmouse** [comment]
> sorry to butt in here @domesticmouse but could you perhaps add a script step that does `sudo apt install ninja-build` ?

Good call, that worked

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon 

I need to land this to complete the codelab write up.

**Review by RedBrogdon — APPROVED** [review]
LGTM. Is there anything we need to do with the Duktape license other than make sure it's included?

**Comment by domesticmouse** [comment]
> LGTM. Is there anything we need to do with the Duktape license other than make sure it's included?

Duktape is MIT licensed (https://github.com/svaarala/duktape/blob/master/LICENSE.txt). Should we add a licenses section to the App UI?

**Pull request merged**
