### PR TITLE
Get to know Firebase with Flutter

### PR DESCRIPTION
**Pull request by domesticmouse**
The first steps of a Getting to know Firebase with Flutter codelab.

### CODE REVIEW

**Comment by domesticmouse** [comment]
@RedBrogdon I am planning on landing this PR so I can properly refer to it from the codelab text. Please let me know if you want me to hold so you can review. Kthnxsbye!

**Comment by kwalrath** [comment]
389 files? Dang!

**Comment by domesticmouse** [comment]
> 389 files? Dang!

Most of it is Android and iOS runner projects 😏

**Comment by domesticmouse** [comment]
Landing =)

**Pull request merged**
