### PR TITLE
Migrate tfagents codelab to Material 3

### PR DESCRIPTION
**Pull request by miquelbeltran**
Migrated tfagents codelab to Material 3

### Before Material 3

Screenshot 2023-01-18 at 16 20 36

Screenshot 2023-01-18 at 16 21 31

### With Material 3

Screenshot 2023-01-18 at 16 21 11

Screenshot 2023-01-18 at 16 21 15

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Maybe it is worth switching the Reset Game button from `ElevatedButton` to `FilledButton`

**Comment by domesticmouse** [comment]
> Maybe it is worth switching the Reset Game button from `ElevatedButton` to `FilledButton`

Sgtm

**Review by domesticmouse — APPROVED** [review]
LGTM once the button is changed

**Comment by domesticmouse** [comment]
FYI @windmaple

**Comment by windmaple** [comment]
LGTM

**Comment by domesticmouse** [comment]
This PR is trailing `main` by 37 commits. Please bring it up to date.

**Comment by miquelbeltran** [comment]
@domesticmouse could this PR be merged?

**Pull request merged**
