### PR TITLE
Add break in switch-case statements

### PR DESCRIPTION
**Pull request by kingcaubalejo**
Added break statements in the code.

*List which issues are fixed by this PR. For larger changes, raising an issue first helps
reduce redundant work.*

## Pre-launch Checklist

- [ ] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
Which version of Dart are you using? Part of the migration to Dart 3 with switch expressions we have removed the need for a trailing `break`.

Please see [`unnecessary_breaks` linter](https://dart.dev/tools/linter-rules/unnecessary_breaks#:~:text=Only%20use%20a%20break%20in,switch%20case%20statements%20are%20unnecessary.) for more detail.

**Comment by kingcaubalejo** [comment]
Ohh I see, what would be the version that I could use?

**Comment by kingcaubalejo** [comment]
Okay got it now.
image


Will try this. Thanks!

**Comment by domesticmouse** [comment]
> Ohh I see, what would be the version that I could use?

I'd also suggest using Flutter stable instead of Flutter master. The master channel will break as things are developed and so forth. See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for more detail

**Comment by domesticmouse** [comment]
> Okay got it now. image
> 
> Will try this. Thanks!

Rather than turning on a single lint, I'd suggest adopting [`flutter_lints`](https://pub.dev/packages/flutter_lints) as a useful set of Flutter lints that will help keep your code tidy.

**Comment by domesticmouse** [comment]
> Rather than turning on a single lint, I'd suggest adopting [`flutter_lints`](https://pub.dev/packages/flutter_lints) as a useful set of Flutter lints that will help keep your code tidy.

I take that back, `unneccessary_breaks` isn't part of `flutter_lints` yet, AFAICT.

**Comment by kingcaubalejo** [comment]
I tried it but gives me error regarding breaks in switch

image

my rebuilding process.

1. flutter clean
2. flutter packages get

image


image

**Comment by kingcaubalejo** [comment]
Sure, will bring back breaks for the meantime.

**Comment by domesticmouse** [comment]
I'm adding `master` CI to this repo so I can better replicate what you are seeing. https://github.com/flutter/codelabs/pull/1924

**Comment by domesticmouse** [comment]
It looks like `namer` is passing CI using the `master` branch. I don't understand why your code is triggering the compiler warning.

**Comment by kingcaubalejo** [comment]
Hmmmmm, I also don't know. I followed this tutorial https://codelabs.developers.google.com/codelabs/flutter-codelab-first#6 and also did some counter checking in the repo with the actual code. I noticed that missing break statements.

**Comment by domesticmouse** [comment]
Want to sign the CLA?

Also, do you have thoughts on this @filiph ?

**Comment by filiph** [comment]
This is definitely weird. My first reaction is either some bug in the compiler (maybe try `flutter clean`?) OR two versions of Flutter/Dart on the system, and one of them taking precedence when building.

@kingcaubalejo, could you please try going to the command line and doing this, in sequence:

 ```terminal
cd path/to/your/project
which flutter
flutter --version
which dart
dart --version
dart analyze
flutter run
```

Please paste the whole output of the terminal.

**Comment by domesticmouse** [comment]
Closing this out as the break is being marked as not required, even on `master` channel.

**Pull request closed without merging**
