### PR TITLE
Patterns and Records for `in_app_purchases` codelab

### PR DESCRIPTION
**Pull request by miquelbeltran**
Initial idea of a possible use of patterns and records in the codelab.

- Use Dart 3 patterns to parse the request JSON or throw an exception if the format is wrong.
- The method returns a Record containing the data.
- The unit test included also uses an object Pattern to extract the productId and type directly.

I will keep this as Draft until ready to merge.
I'd like to get some feedback before applying the change everywhere.

Googlers: CL 532694692

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Comment by miquelbeltran** [comment]
Thank you both! I will apply the changes to all steps, and update the codelab document as well

**Comment by miquelbeltran** [comment]
@domesticmouse the Codelab document has been updated as well, the only change was on page 61 on the `bin/server.dart` file for the dart backend server.

**Review by johnpryan — APPROVED** [review]

**Comment by domesticmouse** [comment]
@miquelbeltran Are you ready for me to land this and the updated codelab text?

PTAL at cl/532694692 @RedBrogdon

**Comment by miquelbeltran** [comment]
> @miquelbeltran Are you ready for me to land this and the updated codelab text?
> 
> PTAL at cl/532694692 @RedBrogdon

Yes, it should be ready to go

**Comment by domesticmouse** [comment]
> > @miquelbeltran Are you ready for me to land this and the updated codelab text?
> 
> > 
> 
> > PTAL at cl/532694692 @RedBrogdon
> 
> 
> 
> Yes, it should be ready to go

I'll land this when the matching codelab text CL is ready to land. Thanks!

**Pull request merged**
