### PR TITLE
Adding in supplemental material for Firebase Summit 2022

### PR DESCRIPTION
**Pull request by nohe427**
This adds in supplemental content for Firebase Summit 2022.

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Ping me when you are ready for this to land

**Comment by nohe427** [comment]
Will do, thank you!

**Comment by domesticmouse** [comment]
QQ: can we land this now?

**Comment by nohe427** [comment]
Sorry for delays. Its good to merge, but I see the beta flutter is failing on a separate codelab. I will take a look at getting that sorted.

**Comment by domesticmouse** [comment]
> Sorry for delays. Its good to merge, but I see the beta flutter is failing on a separate codelab. I will take a look at getting that sorted.

The latest flutter beta has broken a few things. I'll pull it from beta CI and setup a PR with the fix pending stable increment

**Comment by nohe427** [comment]
@domesticmouse - Wrote a fix here : https://github.com/flutter/codelabs/pull/1124

**Pull request merged**
