### PR TITLE
Only warn about analysis and format issues for dev and beta

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by Piinks** [comment]
Are deprecation warnings breaking for this repo? We could update the analysis options rather than skip different branches in CI. I actually have a codelab on the way that won't work here until the next stable release.
I was chatting with @johnpryan and @RedBrogdon about this yesterday.. maybe they have an idea of how to handle CI for things like this and the upcoming codelab?

**Comment by domesticmouse** [comment]
The last time we had deprecation warnings show up in beta and dev, the required support had already shipped to stable. 

If we can update the requirements for deprecation warnings on master to require stable support, then I'd prefer to stay where we are with the requirement that codelab code is warning free across stable, beta and dev.

**Comment by johnpryan** [comment]
Deprecation warnings are info-level, so using [flutter analyze](https://github.com/flutter/codelabs/blob/master/flutter_ci_script_stable.sh#L51) returns a `1` exit code. Using `dart analyze` would treat info-level warnings as non-fatal, so we might consider using that instead.

I don't have a concrete plan to add CI for the DartPad codelabs yet, so for now I think it's okay to add your snippets as-is. We might not be able to enable CI for them until the next stable release, but that's probably okay.

**Comment by johnpryan** [comment]
> Using dart analyze would treat info-level warnings as non-fatal, so we might consider using that instead.

Actually, `flutter analyze --no-fatal-infos` would make more sense.

**Comment by domesticmouse** [comment]
TBR: @Piinks

**Pull request merged**
