### PR TITLE
Drop `firebase-get-to-know-flutter/supplemental` and update `in_app_purchases`

### PR DESCRIPTION
**Pull request by domesticmouse**
Fixes: https://github.com/flutter/flutter/issues/114186

## Pre-launch Checklist

- [x] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @nohe427 and @thatfiredev

**Comment by nohe427** [comment]
Verified with @kroikie . We can remove this and find a better location for the supplemental stuff to live long term.

**Comment by nohe427** [comment]
I am unable to LGTM officially, but LGTM unofficially.

**Comment by domesticmouse** [comment]
Actually this is starting to look like a Flutter 3.3.6 breakage. Or something.

**Review by craiglabenz — APPROVED** [review]
LGTM

**Review by RedBrogdon — APPROVED** [review]

**Pull request merged**
